package com.eminence.eventit.utils

object Constants {
    const val USERBASEURL = "http://bookmysikkimshow.servicewale.co.in/api/user/"
    const val PARTNERBASEURL = "http://bookmysikkimshow.servicewale.co.in/api/merchant/"
    const val IMAGEURL = "http://bookmysikkimshow.servicewale.co.in/images/"
    const val USERSIGNUP = "user_signup"
    const val MYORDER = "my_orders"
    const val ORDERDETAILS = "order_details"
    const val CHECKUSERNAME = "username_availability"
    const val USERLOGIN = "user_login"
    const val BOOKTICKET = "book_ticket"
    const val CARTLIST = "cart_user"
    const val PLAN = "subscription_plan"
    const val SUBSCRIPTIONDISCOUNT = "subscription_details"
    const val SUBSCRIPTION = "add_subscription"
    const val CHECKMEMBERSHIP = "user_subscription_check"
    const val PROFILE = "user_profile"
    const val UPDATEPROFILE = "user_profile_update"
    const val CHANGEPASSWORD = "user_change_password"
    const val APPCONTENT = "content"
    const val MYQR = "myqrcode"
    const val BANNER = "banner_list"
    const val SLIDERLIST = "intro_slider"
    const val CATEGORYList = "category_list"
    const val TOPVISITED = "top_visited_places"
    const val THINGSTODO = "things_to_do"
    const val UPCOMINGEVENT = "upcoming_events"
    const val CATEGORYLISTBYCITY = "places_list"
    const val CATEGORYLISTBYID = "places_list_by_category"
    const val PLACEDETAILS = "place_details"
    const val TIMESLOT = "timeslot_by_activity_event"
    const val EVENTDETAILS = "event_activity_details"
    const val ADDTOCARTADDON = "add_to_cart_addon"
    const val ADDTOCART = "add_to_cart_event_activity"
    const val PLACEDETAILTOTAL = "cart_calculation"

    const val FEEDBACK = "send_feedback"
    const val USERQUERY = "user_enquiry"


    const val PAPULORPARTNERList = "partner_by_rating"
    const val SUBCATEGORYList = "partner_by_category"
    const val STOREDATA = "partner_by_id"
    const val QRHISTORY = "qr_scan_history"
    const val HELP = "user_help"
    const val SENTOTP = "user_otp_send"
    const val VERIFYOTP = "user_otp_verify"
    const val RESENDOTP = "user_resend_otp"
    const val QUERY = "user_query"
    const val NOTIFICATION = "user_notification"
    const val SHARED_CART_ITEM = "cartitem"


    //Partner
    const val PARTNERCATEGORY = "category_list"
    const val PARTNERSTATE = "states"
    const val PARTNERSIGNUP = "partner_signup"
    const val PARTNERLOGIN = "partner_login"
    const val PARTNERPROFILE = "partner_profile"
    const val PARTNERAPPCONTENT = "content"
    const val PARTNERCHANGEPASSWORD = "partner_change_password"
    const val PARTNERQRCODE = "scan_qr_code"
    const val PARTNERQRHISTORY = "qr_scan_history"
    const val PARTNERHELP = "partner_help"
    const val PARTNERSENTOTP = "partner_otp_send"
    const val PARTNERVERIFYOTP = "partner_otp_verify"
    const val PARTNERRESENDOTP = "partner_resend_otp"
    const val PARTNERQUERY = "partner_query"
    const val DISCOUNT = "discount_partner"
    const val PARTNERNOTIFICATION = "partner_notification"

}